name: mobility_one
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pedantic: ^1.11.1
  sentry: ^5.1.0
  connectivity_plus: ^1.0.6
  equatable: ^2.0.3
  shared_preferences: ^2.0.6
  flutter_bloc: ^7.0.1
  intl: ^0.17.0
  html: ^0.15.0
  oauth2: ^2.0.0
  universal_io: ^2.0.4
  device_info_plus: ^2.1.0
  package_info_plus: ^1.0.4
  beamer: ^0.14.1
  fl_chart: ^0.36.3
  table_calendar: ^3.0.1
  validators: ^3.0.0
  flutter_simple_treeview: 3.0.0-nullsafety.1
  # For localizations and string translations
  intl_generator: ^0.2.0+0
  path_provider:
  path:
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  flip_card: ^0.5.0
  pluto_grid: ^2.4.1
  excel: ^2.0.0-null-safety-3
  file_picker: ^4.0.2
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/kpiCardNegativeGraph.png
    - assets/images/kpiCardPositiveGraph.png
    - assets/images/notification_button.svg
    - assets/images/settings_button.svg
    - assets/images/mobility_one_logo.svg
    - assets/images/search_button.svg
    - assets/images/profile.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: Averta
#      fonts:
#        - asset: assets/fonts/Averta-Regular.ttf
#        - asset: assets/fonts/Averta-Italic.ttf
#          style: italic

# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
